#
# Apache v2 license
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

openapi: 3.0.0
info:
  description: Visual Pipeline and Platform Evaluation REST API
  title: Visual Pipeline and Platform Evaluation REST API
  version: 3.1.0
servers:
- url: /
paths:
  /pipelines:
    get:
      description: Return supported pipelines
      operationId: pipelines_get
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Pipeline'
                type: array
          description: Success
      x-openapi-router-controller: src.rest_api.endpoints.Endpoints
    post:
      description: Create new pipeline
      operationId: pipelines_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PipelineDefinition'
        required: true
      responses:
        "201":
          description: "Pipeline created"
          headers:
            Location:
              description: The location of the newly created pipeline
              schema:
                type: string
                format: uri
      x-openapi-router-controller: src.rest_api.endpoints.Endpoints
  /pipelines/validate:
    post:
      description: Validate pipeline
      operationId: pipelines_validate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PipelineValidation'
        required: true
      responses:
        "200":
          description: "Pipeline valid"
        "400":
          description: "Pipeline invalid"
          content:
            text/plain: # TODO: change to JSON
              schema:
                type: string
                example: invalid launch string
      x-openapi-router-controller: src.rest_api.endpoints.Endpoints
  /pipelines/{name}/{version}/run:
    post:
      description: Run new pipeline instance.
      operationId: pipelines_name_version_run
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: version
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PipelineRequestRun'
        required: true
      responses:
        200:
          description: Success
      x-openapi-router-controller: src.rest_api.endpoints.Endpoints
  /pipelines/{name}/{version}/benchmark:
    post:
      description: Run Platform Ceiling Analysis.
      operationId: pipelines_name_version_benchmark
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: version
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PipelineRequestBenchmark'
        required: true
      responses:
        200:
          description: Success
      x-openapi-router-controller: src.rest_api.endpoints.Endpoints
  /pipelines/{name}/{version}/optimize:
    post:
      description: Optimize Pipeline.
      operationId: pipelines_name_version_optimize
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: version
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PipelineRequestOptimize'
        required: true
      responses:
        200:
          description: Success
      x-openapi-router-controller: src.rest_api.endpoints.Endpoints
  /pipelines/{name}/{version}:
    delete:
      description: Delete pipeline.
      operationId: pipelines_name_version_delete
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: version
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          description: Pipeline deleted
        400:
          description: Cannot delete pipeline # TODO: add reason
      x-openapi-router-controller: src.rest_api.endpoints.Endpoints
  /pipelines/status:
    get:
      description: Returns all pipeline instance status.
      operationId: pipelines_status_get_all
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PipelineInstanceStatus'
                type: array
          description: Success
      x-openapi-router-controller: src.rest_api.endpoints.Endpoints
  /pipelines/{instance_id}:
    delete:
      description: Stop pipeline instance.
      operationId: pipelines_instance_id_delete
      parameters:
      - explode: false
        in: path
        name: instance_id
        required: true
        schema:
          type: string
          format: uuid
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PipelineInstanceStatus'
                type: array
          description: Success
      x-openapi-router-controller: src.rest_api.endpoints.Endpoints
    get:
      description: Return pipeline instance summary.
      operationId: pipelines_instance_id_get
      parameters:
      - explode: false
        in: path
        name: instance_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PipelineInstanceSummary'
          description: Success
      x-openapi-router-controller: src.rest_api.endpoints.Endpoints
  /pipelines/{instance_id}/status:
    get:
      description: Return pipeline instance status.
      operationId: pipelines_instance_id_status_get
      parameters:
      - explode: false
        in: path
        name: instance_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PipelineInstanceStatus'
          description: Success
      x-openapi-router-controller: src.rest_api.endpoints.Endpoints
  /devices:
    get:
      description: Return available devices.
      operationId: devices_get
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Device'
                type: array
          description: Success
      x-openapi-router-controller: src.rest_api.endpoints.Endpoints
  /models:
    get:
      description: Return installed models.
      operationId: models_get
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Model'
                type: array
          description: Success
      x-openapi-router-controller: src.rest_api.endpoints.Endpoints
  /metrics:
    get:
      description: Return current metrics.
      operationId: metrics_get
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/MetricSample'
                type: array
          description: Success
      x-openapi-router-controller: src.rest_api.endpoints.Endpoints
components:
  schemas:
    AnyValue: {}
    Pipeline:
      example:
        name: name
        version: version
        description: description
        type: GStreamer
        parameters:
          key:
            default: ""
      properties:
        name:
          type: string
        version:
          type: string
        description:
          type: string
        type:
          enum:
          - GStreamer
          type: string
        parameters:
          additionalProperties:
            $ref: '#/components/schemas/PipelineParameters'
          type: object
      required:
      - description
      - type
      type: object
    PipelineDefinition:
      example:
        name: name
        version: version
        description: description
        type: GStreamer
        launch_string: launch_string
        parameters:
          key:
            default: ""
      properties:
        name:
          type: string
        version:
          type: string
        description:
          type: string
        type:
          enum:
          - GStreamer
          type: string
        launch_string:
          type: string
        parameters:
          additionalProperties:
            $ref: '#/components/schemas/PipelineParameters'
          type: object
      required:
      - name
      - version
      - type
      - launch_string
      type: object
    PipelineValidation:
      example:
        type: GStreamer
        launch_string: launch_string
        parameters:
          key:
            default: ""
      properties:
        type:
          enum:
          - GStreamer
          type: string
        launch_string:
          type: string
        parameters:
          additionalProperties:
            $ref: '#/components/schemas/PipelineParameters'
          type: object
      required:
      - type
      - launch_string
      type: object
    PipelineInstanceStatus:
      example:
        start_time: 1
        elapsed_time: 5
        id: 0
        state: RUNNING
        total_fps: 8.531199098924418
        per_stream_fps: 8.531199098924418
        ai_streams: 1
        non_ai_streams: 0
      properties:
        id:
          format: int32
          type: integer
        state:
          enum:
          - RUNNING
          - COMPLETED
          - ERROR
          - ABORTED
          type: string
        total_fps:
          type: number
        per_stream_fps:
          type: number
        ai_streams:
          type: number
        non_ai_streams:
          type: number
        start_time:
          description: Time in seconds since the epoch.
          format: int32
          type: integer
        elapsed_time:
          description: Elapsed time in seconds.
          format: int32
          type: integer
      required:
      - elapsed_time
      - id
      - start_time
      - state
      type: object
    PipelineInstanceSummary:
      example:
        request:
          destination: {}
          source: {}
          parameters: {}
          tags: {}
        id: 0
        type: type
      properties:
        id:
          format: int32
          type: integer
        request:
          $ref: '#/components/schemas/PipelineRequestRun' #TODO: adjust to different Pipeline Requests
        type:
          type: string
      required:
      - id
      - request
      - type
      type: object
    URISource:
      properties:
        type:
          enum:
          - uri
          type: string
        uri:
          format: uri
          type: string
        properties:
          type: object
        capsfilter:
          type: string
        postproc:
          type: string
      required:
      - type
      - uri
      type: object
    GstSource:
      properties:
        type:
          enum:
          - gst
          type: string
        element:
          type: string
        properties:
          type: object
        capsfilter:
          type: string
        postproc:
          type: string
      required:
      - type
      - element
      type: object
    FileDestination:
      properties:
        type:
          enum:
          - file
          type: string
        path:
          format: path
          type: string
      required:
      - type
      - path
      type: object
    KafkaDestination:
      properties:
        host:
          description: Comma seperated list of host:port to use as boostrap servers.
          type: string
        topic:
          type: string
        type:
          enum:
          - kafka
          type: string
      required:
        - host
        - topic
      type: object
    OPCUADestination:
      properties:
        type:
          enum:
          - opcua
          type: string
        variable:
          type: string
        publish_frame:
          type: boolean
      required:
      - type
      - variable
      type: object
    MQTTDestination:
      anyOf:
        - type: object
          properties:
            host:
              description: host:port to use as mqtt server.
              type: string
            topic:
              type: string
            type:
              enum:
              - mqtt
              type: string
          required:
            - host
            - topic
            - type
        - type: object
          properties:
            publish_frame:
              type: boolean
            topic:
              type: string
            type:
              enum:
              - mqtt
              type: string
          required:
            - topic
            - type
    RTSPDestination:
      properties:
        type:
          enum:
          - rtsp
          type: string
        path:
          type: string
          minLength: 1
          pattern: "^[a-zA-Z0-9][a-zA-Z0-9_/-]*[a-zA-Z0-9]$"
      required:
        - type
        - path
      type: object
    WebRTCDestination:
      properties:
        type:
          enum:
          - webrtc
          type: string
        peer-id:
          type: string
          minLength: 1
          pattern: "^[a-zA-Z0-9][a-zA-Z0-9_/-]*[a-zA-Z0-9]$"
      required:
        - type
        - peer-id
      type: object
    S3_write:
      properties:
        type:
          enum:
          - s3_write
          type: string
        bucket:
          type: string
        folder_prefix:
          type: string
        block:
          type: boolean
      required:
        - type
        - bucket
        - folder_prefix
      type: object
    InfluxWrite:
      properties:
        type:
          enum:
          - influx_write
          type: string
        bucket:
          type: string
        org:
          type: string
        measurement:
          type: string
      required:
        - type
        - bucket
        - org
      type: object
    ROS2Destination:
      anyOf:
        - type: object
          properties:
            topic:
              type: string
            type:
              enum:
              - ros2
              type: string
          required:
            - topic
            - type
        - type: object
          properties:
            publish_frame:
              type: boolean
            topic:
              type: string
            type:
              enum:
              - ros2
              type: string
          required:
            - topic
            - type
    FrameDestination:
      anyOf:
        - type: object
          discriminator:
            propertyName: type
          oneOf:
            - $ref: '#/components/schemas/RTSPDestination'
            - $ref: '#/components/schemas/WebRTCDestination'
            - $ref: '#/components/schemas/S3_write'
        - type: array
          items:
            discriminator:
              propertyName: type
            oneOf:
              - $ref: '#/components/schemas/RTSPDestination'
              - $ref: '#/components/schemas/WebRTCDestination'
              - $ref: '#/components/schemas/S3_write'
    MetadataDestination:
      anyOf:
        - type: object
          discriminator:
            propertyName: type
          oneOf:
            - $ref: '#/components/schemas/KafkaDestination'
            - $ref: '#/components/schemas/MQTTDestination'
            - $ref: '#/components/schemas/FileDestination'
            - $ref: '#/components/schemas/OPCUADestination'
            - $ref: '#/components/schemas/InfluxWrite'
            - $ref: '#/components/schemas/ROS2Destination'
        - type: array
          items:
            discriminator:
              propertyName: type
            oneOf:
              - $ref: '#/components/schemas/KafkaDestination'
              - $ref: '#/components/schemas/MQTTDestination'
              - $ref: '#/components/schemas/FileDestination'
              - $ref: '#/components/schemas/OPCUADestination'
              - $ref: '#/components/schemas/InfluxWrite'
              - $ref: '#/components/schemas/ROS2Destination'
    FrameAndMetadataDestination:
      type: object
      properties:
        frame:
          $ref: '#/components/schemas/FrameDestination'
        metadata:
          $ref: '#/components/schemas/MetadataDestination'
      required:
        - frame
        - metadata
      additionalProperties: false
    FrameORMetadataDestination:
      anyOf:
        - type: object
          properties:
            frame:
              $ref: '#/components/schemas/FrameDestination'
          required:
            - frame
          additionalProperties: false
        - type: object
          properties:
            metadata:
              $ref: '#/components/schemas/MetadataDestination'
          required:
            - metadata
          additionalProperties: false
    PipelineRequestRun: #TODO redefine
      example:
        async: true
        source:
          type: uri
          uri: file:///root/video-examples/example.mp4
        parameters: {}
        tags: {}
      properties:
        async:
          description: Indicates whether the inference operation is executed asynchronously or synchronously. Default value is true.
          type: boolean
        source:
          discriminator:
            propertyName: type
          oneOf:
           - $ref: '#/components/schemas/URISource'
           - $ref: '#/components/schemas/GstSource'
          type: object
        destination:
          oneOf:
            - $ref: '#/components/schemas/FrameAndMetadataDestination'
            - $ref: '#/components/schemas/FrameORMetadataDestination'
          type: object
        tags:
          description: Client specified values. Returned with results.
          type: object
        parameters:
          description: Pipeline specific parameters.
          type: object
      type: object
    PipelineRequestBenchmark: #TODO redefine
      example:
        async: true
        source:
          type: uri
          uri: file:///root/video-examples/example.mp4
        parameters: {}
        tags: {}
      properties:
        async:
          description: Indicates whether the inference operation is executed asynchronously or synchronously. Default value is true.
          type: boolean
        source:
          discriminator:
            propertyName: type
          oneOf:
           - $ref: '#/components/schemas/URISource'
           - $ref: '#/components/schemas/GstSource'
          type: object
        destination:
          oneOf:
            - $ref: '#/components/schemas/FrameAndMetadataDestination'
            - $ref: '#/components/schemas/FrameORMetadataDestination'
          type: object
        tags:
          description: Client specified values. Returned with results.
          type: object
        parameters:
          description: Pipeline specific parameters.
          type: object
      type: object
    PipelineRequestOptimize: #TODO redefine
      example:
        async: true
        source:
          type: uri
          uri: file:///root/video-examples/example.mp4
        parameters: {}
        tags: {}
      properties:
        async:
          description: Indicates whether the inference operation is executed asynchronously or synchronously. Default value is true.
          type: boolean
        source:
          discriminator:
            propertyName: type
          oneOf:
           - $ref: '#/components/schemas/URISource'
           - $ref: '#/components/schemas/GstSource'
          type: object
        destination:
          oneOf:
            - $ref: '#/components/schemas/FrameAndMetadataDestination'
            - $ref: '#/components/schemas/FrameORMetadataDestination'
          type: object
        tags:
          description: Client specified values. Returned with results.
          type: object
        parameters:
          description: Pipeline specific parameters.
          type: object
      type: object
    PipelineParameters:
      example:
        default: {}
      properties:
        default: {}
    Device:
      example:
        device_name: GPU.0
        full_device_name: Intel(R) Arc(TM) Graphics (iGPU)
        device_type: Integrated
        device_family: GPU
        gpu_id: 0
      properties:
        device_name:
          type: string
        full_device_name:
          type: string
        device_type:
          type: string
        device_family:
          type: string
        gpu_id:
          type: integer
      required:
      - description
      - type
      type: object
    Model:
      example:
        name: ssdlite_mobilenet_v2_INT8
        display_name: SSDLite MobileNet V2 (INT8)
        category: Detection
        precision: INT8
      properties:
        name:
          type: string
        display_name:
          type: string
        category:
          type: string
        precision:
          type: string
      required:
      - name
      - display_name
      - category
      type: object
    MetricSample: #TODO: redefine
      example:
        name: fps
        description: Frames per second
        timestamp: 1625247600
        value: 75.5
      properties:
        name:
          type: string
        description:
          type: string
        timestamp:
          type: number
        value:
          type: number
      required:
      - timestamp
      - value
      type: object